version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true
artifacts:
  files:
    - bin/Release/net7.0/win-x64/publish/Lumberjack.exe
  discard-paths: yes
