version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS --install-dir $HOME/.dotnet
      - export DOTNET_ROOT=$HOME/.dotnet
  build:
    commands:
      - ls $HOME
      - dotnet -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false
artifacts:
  files:
    - bin/Release/net7.0/win-x64/publish/Lumberjack.exe
