version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - bin/Release/net7.0/win-x64/publish/Lumberjack.exe
